<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PenerimaBansosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id_penerimabansos' => 1,
                'id_jenisbansos' => 1,
                'id_petugas' => 1,
                'id_admin' => 1,
                'no_kk' => '1234567890',
                'nik' => '1234567890123456',
                'agama' => 'Islam',
                'alamat' => 'Jl. Contoh No. 123',
                'no_telp' => '081234567890',
                'status_pekerjaan' => 'Bekerja',
                'pekerjaan' => 'PNS',
                'jml_penghasilan' => 5000000,
                'jml_tanggungan' => 3,
                'history_penerimaan' => 'Pernah Menerima',
                'tempat_tinggal' => 'Rumah Sendiri',
                'pendidikan' => 'SMA',
                'jenis_bansos' => 'BPNT',
                'keterangan' => 'Keterangan 1',
            ],
            [
                'id_penerimabansos' => 2,
                'id_jenisbansos' => 1,
                'id_petugas' => 1,
                'id_admin' => 1,
                'no_kk' => '2345678901',
                'nik' => '2345678901234567',
                'agama' => 'Islam',
                'alamat' => 'Jl. Dummy No. 456',
                'no_telp' => '082345678901',
                'status_pekerjaan' => 'Tidak Bekerja',
                'pekerjaan' => '',
                'jml_penghasilan' => null,
                'jml_tanggungan' => 4,
                'history_penerimaan' => 'Belum Menerima',
                'tempat_tinggal' => 'Kontrakan',
                'pendidikan' => 'SD',
                'jenis_bansos' => 'BPNT',
                'keterangan' => 'Keterangan 2',
            ],
            [
                'id_penerimabansos' => 3,
                'id_jenisbansos' => 2,
                'id_petugas' => 1,
                'id_admin' => 1,
                'no_kk' => '3456789012',
                'nik' => '3456789012345678',
                'agama' => 'Protestan',
                'alamat' => 'Jl. Contoh No. 789',
                'no_telp' => '083456789012',
                'status_pekerjaan' => 'Bekerja',
                'pekerjaan' => 'Wiraswasta',
                'jml_penghasilan' => 1500000,
                'jml_tanggungan' => 2,
                'history_penerimaan' => 'Pernah Menerima',
                'tempat_tinggal' => 'Kontrakan',
                'pendidikan' => 'SMP',
                'jenis_bansos' => 'BLT',
                'keterangan' => 'Keterangan 3',
            ],
            [
                'id_penerimabansos' => 4,
                'id_jenisbansos' => 2,
                'id_petugas' => 1,
                'id_admin' => 1,
                'no_kk' => '4567890123',
                'nik' => '4567890123456789',
                'agama' => 'Katholik',
                'alamat' => 'Jl. Dummy No. 101112',
                'no_telp' => '084567890123',
                'status_pekerjaan' => 'Bekerja',
                'pekerjaan' => 'Guru',
                'jml_penghasilan' => 2000000,
                'jml_tanggungan' => 4,
                'history_penerimaan' => 'Pernah Menerima',
                'tempat_tinggal' => 'Rumah Sendiri',
                'pendidikan' => 'SMA',
                'jenis_bansos' => 'BLT',
                'keterangan' => 'Keterangan 4',
            ],
            [
                'id_penerimabansos' => 5,
                'id_jenisbansos' => 3,
                'id_petugas' => 1,
                'id_admin' => 1,
                'no_kk' => '5678901234',
                'nik' => '5678901234567890',
                'agama' => 'Islam',
                'alamat' => 'Jl. Contoh No. 131415',
                'no_telp' => '085678901234',
                'status_pekerjaan' => 'Tidak Bekerja',
                'pekerjaan' => '',
                'jml_penghasilan' => null,
                'jml_tanggungan' => 1,
                'history_penerimaan' => 'Belum Menerima',
                'tempat_tinggal' => 'Menumpang',
                'pendidikan' => 'Tidak Sekolah',
                'jenis_bansos' => 'PKH',
                'keterangan' => 'Keterangan 5',
            ],
            [
                'id_penerimabansos' => 6,
                'id_jenisbansos' => 3,
                'id_petugas' => 1,
                'id_admin' => 1,
                'no_kk' => '6789012345',
                'nik' => '6789012345678901',
                'agama' => 'Budha',
                'alamat' => 'Jl. Dummy No. 161718',
                'no_telp' => '086789012345',
                'status_pekerjaan' => 'Bekerja',
                'pekerjaan' => 'Karyawan',
                'jml_penghasilan' => 1000000,
                'jml_tanggungan' => 2,
                'history_penerimaan' => 'Pernah Menerima',
                'tempat_tinggal' => 'Kontrakan',
                'pendidikan' => 'SD',
                'jenis_bansos' => 'PKH',
                'keterangan' => 'Keterangan 6',
            ],
            [
                'id_penerimabansos' => 7,
                'id_jenisbansos' => 4,
                'id_petugas' => 1,
                'id_admin' => 1,
                'no_kk' => '7890123456',
                'nik' => '7890123456789012',
                'agama' => 'Islam',
                'alamat' => 'Jl. Contoh No. 192021',
                'no_telp' => '087890123456',
                'status_pekerjaan' => 'Bekerja',
                'pekerjaan' => 'Pegawai Swasta',
                'jml_penghasilan' => 1800000,
                'jml_tanggungan' => 3,
                'history_penerimaan' => 'Belum Menerima',
                'tempat_tinggal' => 'Rumah Sendiri',
                'pendidikan' => 'SMP',
                'jenis_bansos' => 'BSB',
                'keterangan' => 'Keterangan 7',
            ],
            [
                'id_penerimabansos' => 8,
                'id_jenisbansos' => 4,
                'id_petugas' => 1,
                'id_admin' => 1,
                'no_kk' => '8901234567',
                'nik' => '8901234567890123',
                'agama' => 'Katholik',
                'alamat' => 'Jl. Dummy No. 222324',
                'no_telp' => '088901234567',
                'status_pekerjaan' => 'Bekerja',
                'pekerjaan' => 'Pedagang',
                'jml_penghasilan' => 2200000,
                'jml_tanggungan' => 2,
                'history_penerimaan' => 'Pernah Menerima',
                'tempat_tinggal' => 'Kontrakan',
                'pendidikan' => 'Kuliah',
                'jenis_bansos' => 'BSB',
                'keterangan' => 'Keterangan 8',
            ],
        ];
        DB::table('penerima_bansos')->insert($data);
    }
}
